config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: %i[index edit show update]
  resources :courses
  root 'home#index'

  get 'privacy_policy', to: 'home#privacy_policy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  LEVELS = %i[Beginner Intermediate Advanced]
  LANGUAGES = %i[English Spanish French]
  has_rich_text :description

  belongs_to :user

  validates :title, :short_description, :language, :price, :level, presence: true
  validates :description, presence: true, length: { :minimum => 5 }

  def to_s
    title
  end

  class << self
    def languages
      LANGUAGES.map { |language| [language, language] }
    end

    def levels
      LEVELS.map { |level| [level, level] }
    end
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, join_table: :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  
  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  validates :name, presence: true, uniqueness: true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable

  has_many :courses

  after_create :assign_default_role

  validate :must_have_a_role, on: :update

  def to_s
    email
  end

  def username
    email.split(/@/).first
  end

  private

  def assign_default_role
    self.add_role(:student) if self.roles.blank?
    self.add_role(:teacher)
  end

  def must_have_a_role
    if roles.blank?
      errors.add(:roles, 'must have at least one role')
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_action :authenticate_user!

  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  before_action :set_global_variables, if: :user_signed_in?

  def set_global_variables
    # navbar search
    @ransack_courses = Course.ransack(params[:courses_search], search_key: :courses_search)
  end

  private

  def user_not_authorized
    flash[:alert] = 'You are not authorized to perform this action.'
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy ]

  # GET /courses or /courses.json
  def index
    @ransack_courses = Course.ransack(params[:courses_search], search_key: :courses_search)
    @courses = @ransack_courses.result.includes(:user)
  end

  # GET /courses/1 or /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
    authorize @course
  end

  # GET /courses/1/edit
  def edit
    authorize @course
  end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)
    @course.user = current_user
    authorize @course

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    authorize @course

    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    authorize @course

    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:title, :description, :short_description, :language, :level, :price)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:index]

  def index
    @courses = Course.all.limit(3)
    @top_rated_courses = Course.limit(3).order('RANDOM()')
    @latest_courses = Course.all.limit(3).order(created_at: :desc)
  end

  def landing_page
  end

  def privacy_policy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :fetch_user, only: [:edit, :update]

  def index
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true).order(created_at: :desc)
  end

  def edit
    authorize @user
  end

  def update
    authorize @user

    if @user.update(user_params)
      redirect_to users_path, notice: "User #{@user.email} was successfully updated."
    else
      render :edit
    end
  end

  private

  def fetch_user
    @user ||= User.find(params[:id])
  end

  def user_params
    params.require(:user).permit({ role_ids: [] })
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/courses/_course.html.haml
.card
  .card-header
    .fa.fa-book
    = link_to course.title, course_path(course)
  .card-body
    = course.short_description
  .card-footer
    .fa.fa-globe-americas
    = course.language
    .fa.fa-signal
    = course.level
    .fa.fa-money
    = number_to_currency(course.price)
  .card-footer
    .far.fa-clock
    = course.created_at.strftime('%d-%b-%Y')
    .row
    .fa.fa-chalkboard-teacher
    = course.user.username
  - if current_user && policy(course).edit?
    .card-footer
      = link_to 'Show', course, class: 'btn btn-sm btn-primary'
      = link_to 'Edit', edit_course_path(course), class: 'btn btn-sm btn-warning'
      = link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger'

app/views/courses/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@course) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title
    = f.input :description, as: :rich_text_area
    = f.input :short_description
    = f.input :language, collection: Course.languages, include_blank: false
    = f.input :level, collection: Course.levels, include_blank: false
    = f.input :price

  .form-actions
    = f.button :submit

app/views/courses/edit.html.haml
.card
  .card-header
    %h1 Editing course
  .card-body
    = render 'form'

= link_to 'Show', @course
\|
= link_to 'Back', courses_path

app/views/courses/index.html.haml
%h1
  Courses
  = "(#{@courses.count})"

.row
  .col-md-2
    = search_form_for @ransack_courses, as: :courses_search, url: courses_path do |f|
      = f.label :title
      = f.search_field :title_cont, placeholder: 'Title', class: 'form-control form-control-sm'
      = f.label :description
      = f.search_field :short_description_cont, placeholder: 'Description', class: 'form-control form-control-sm'
      = f.label :language
      = f.select :language_cont, Course.languages, include_blank: true
      = f.label :level
      = f.select :level_cont, Course.levels, include_blank: true
      = f.label :price
      = f.search_field :price_eq, placeholder: 'Price', class: 'form-control form-control-sm'
      = f.label :teacher
      = f.search_field :user_email_cont, placeholder: 'Email', class: 'form-control form-control-sm'
      = f.submit

    = link_to 'Clear', courses_path, class: 'btn btn-secondary'

  .col-md-10
    .card-columns
      = render @courses

app/views/courses/new.html.haml
.card
  .card-header
    %h1 New course
  .card-body
    = render 'form'

= link_to 'Back', courses_path

app/views/courses/show.html.haml
= link_to 'Courses', courses_path
\/
= link_to @course.title, course_path(@course)
%p
= render 'courses/course', course: @course

app/views/home/index.html.haml
.jumbotron
  .display-4
    What do you want to learn today?

  .p-4

  - if current_user
    = search_form_for @ransack_courses, as: :courses_search, url: courses_path do |f|
      .input-group
        = f.search_field :title_cont, class: 'form-control-sm', style: 'float: left; width: 250px; ', placeholder: 'Find a course', :autocomplete => :off
        %span.input-group-append
          %button.btn.btn-primary.btn-sm{:type => "submit"}
            %span.fa.fa-search{"aria-hidden" => "true"}

.card-group
  .card.card-body
    %h1
      .fa.fa-graduation-cap
    = Course.count
    online courses
    .row
    Explore a variety of fresh topics
  .card.card-body
    %h1
      .fa.fa-chalkboard-teacher
    = Course.distinct.count(:user_id)
    expert instructors
    .row
    Find the right instructor for you
  .card.card-body
    %h1
      .fa.fa-user-graduate
    = User.count
    active learners
    .row
    Join the knowledge sharing community
  .card.card-body
    %h1
      .fa.fa-infinity
    Lifetime access
    .row
    Learn on your schedule

%hr
%h2
  Popular courses

.card-columns
  = render @courses

%hr
%h2
  Top rated courses

.card-columns
  = render @top_rated_courses

%hr
%h2
  Latest courses

.card-columns
  = render @latest_courses

app/views/home/landing_page.html.haml
.container-fluid
  %h1 Home#landing_page
  %p Find me in app/views/home/landing_page.html.erb
  = link_to 'Privacy Policy', privacy_policy_path

  = link_to courses_path, class: 'btn btn-primary' do
    %i.fas.fa-book-open
    Courses

app/views/home/privacy_policy.html.haml
%h1 Home#privacy_policy
%p Find me in app/views/home/privacy_policy.html.erb
= link_to 'Home', root_path

app/views/layouts/_footer.html.haml
%footer.bg-dark.p-2
  .container.text-center
    .row
      .col-md-4
        Copyright
        ©
        = Time.now.year
        RubyGems Bootcamp
        .row
      .col-md-4
        Privacy policy
        .row
        Terms and conditions
      .col-md-4
        About us
        .row
        = link_to 'New course', new_course_path

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  %a.navbar-brand{:href => "#"} Rubygems
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    - if current_user
      %ul.navbar-nav.mr-auto
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(root_path)}"}
          = link_to root_path, class: 'nav-link' do
            .fa.fa-home
            Home
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(users_path)}"}
          = link_to users_path, class: 'nav-link' do
            .fa.fa-user
            Users
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(courses_path)}"}
          = link_to courses_path, class: 'nav-link' do
            .fa.fa-book
            Courses
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(new_course_path)}"}
          = link_to new_course_path, class: 'nav-link' do
            .fa.fa-plus
            New Course
      = search_form_for @ransack_courses, as: :courses_search, url: courses_path do |f|
        .input-group
          = f.search_field :title_cont, class: 'form-control-sm', style: 'float: left; width: 250px; ', placeholder: 'Find a course', :autocomplete => :off
          %span.input-group-append
            %button.btn.btn-primary.btn-sm{:type => "submit"}
              %span.fa.fa-search{"aria-hidden" => "true"}
      %ul.navbar-nav.mr-right
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(root_path)}"}
          = link_to root_path, class: 'nav-link' do
            .fa.fa-home
            Another link
        %li.nav-item.dropdown
          %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            %b= current_user.email
          .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "navbarDropdown"}
            = link_to edit_user_registration_path, class: "dropdown-item" do
              .fa.fa-cog
              %b Account settings
            = link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do
              .fa.fa-sign-out-alt
              %b Sign out
    - else
      %ul.navbar-nav
        %li.nav-item= link_to 'Sign Up', new_user_registration_path, class: 'nav-link'
        %li.nav-item= link_to 'Log In', new_user_session_path, class: 'nav-link'

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{ class: "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", role: "alert" }
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title RubyGemsBootcamp
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'
    = render 'layouts/messages'

    .container
      %p
      = yield

    = render 'layouts/footer'

app/views/static_pages/landing_page.html.haml
.container-fluid
  %h1 StaticPages#landing_page
  %p Find me in app/views/static_pages/landing_page.html.erb
  = link_to 'Privacy Policy', privacy_policy_path

  = link_to courses_path, class: 'btn btn-primary' do
    %i.fas.fa-book-open
    Courses

app/views/users/_user.html.haml
.card
  .card-header
    .fa.fa-user
    = user.email
  .card-footer
    Signed up
    = time_ago_in_words(user.created_at)
    ago
  .card-footer
    .row.ml-n1
      %b= 'sign_in_count'.humanize + ':'
      = user.sign_in_count
    .row.ml-n1
      %b= 'current_sign_in_at'.humanize + ':'
      = user.current_sign_in_at
    .row.ml-n1
      %b= 'last_sign_in_at'.humanize + ':'
      = user.last_sign_in_at
    .row.ml-n1
      %b= 'current_sign_in_ip'.humanize + ':'
      = user.current_sign_in_ip
    .row.ml-n1
      %b= 'last_sign_in_ip'.humanize + ':'
      = user.last_sign_in_ip
  .card-footer
    - user.roles.each do |role|
      .badge.badge-info
        = role.name
    = link_to 'Edit roles', edit_user_path(user), class: 'btn btn-sm btn-warning' if policy(user).edit?

app/views/users/edit.html.haml
.card
  .card-header
    Editing roles for
    = @user.email
  .card-body
    = simple_form_for @user do |f|
      = f.collection_check_boxes :role_ids, Role.all, :id, :name
      = f.error :roles, class: 'text-danger'
      %hr
      = f.button :submit, class: "btn btn-success"
  .card-footer
    = link_to 'Cancel', users_path, class: 'btn btn-danger'

app/views/users/index.html.haml
%h1
  Users
  = "(#{@users.count})"

.card-columns
  = render @users

.form-inline
  = search_form_for @q do |f|
    = f.search_field :email_cont, placeholder: 'email'
    = f.submit
    = link_to 'Clear', users_path, class: 'btn btn-secondary'

%table.table.table-bordered
  %thead
    %tr
      %th id
      %th= sort_link(@q, :email)
      %th created_at
      %th= 'sign_in_count'.humanize
      %th= 'current_sign_in_at'.humanize
      %th= 'last_sign_in_at'.humanize
      %th= 'current_sign_in_ip'.humanize
      %th= 'last_sign_in_ip'.humanize
  %tbody
    - @users.each do |user|
      %tr
        %td= user.id
        %td= user.email
        %td= user.created_at
        %td= user.sign_in_count
        %td= user.current_sign_in_at
        %td= user.last_sign_in_at
        %td= user.current_sign_in_ip
        %td= user.last_sign_in_ip